### ISSUE TITLE
Losing tech in cargo after losing the techbase and docking

### ISSUE THREAD

**Issue by kgersen** [kgersen/Allegiance#125]
Tech you have loaded in cargo is lost after you dock and you no longer have the techbase that tech is from.

Say you have hunter3 loaded in your cargo spaces and your tac dies. If you dock at a base to repair your hull/energy or whatever your hunter3 in cargo is all replaced by hunter1 and you only keep the ones you had loaded in the missile slot.

It would be better if you could keep your cargo unmodified.

 _Imported from trac ticket #128,  created by anonymous on 07-09-2010 at 00:54, last modified: 11-24-2012 at 02:53_

**Comment by kgersen** [comment]
Might have been fixed with AaronMoore's saved loadout feature.  Needs to be tested post-R6 to confirm.

_Trac comment by TurkeyXIII on 05-30-2011 at 12:17_

**Comment by kgersen** [comment]
I believe occasionally your mounted stuff reverts as well. I've personally docked a mg3 heavy int and relaunched a mg1 heavy int after a destroyed exp.

However it's not reproducible.

_Trac comment by Spunky on 08-28-2012 at 05:58_

**Comment by LordBlacksun** [comment]
Not very important imho
