### ISSUE TITLE
Tracking Guns

### ISSUE THREAD

**Issue by kgersen** [kgersen/Allegiance#136]
I'm on a spree here! All the core changes that I've thought of that should be all done at once so we're not changing the cores every release. (See tickets #77, #137, #138)

A "Tracking" gun could be an interesting concept and might not be exceptionally difficult to implement - Just bastardize some of the missile coding. The only things I can think of off the top of my head that would need to be added are the turning things, accel of a missile, and how well it tracks (For missiles, this is how "locked" it is, but for a gun you could go with a set amount)

This could lead to some interesting things, such as towers with actual missile launchers, turrets with missiles, multiple missile launchers, etc. 

 _Imported from trac ticket #139,  created by Andon on 07-13-2010 at 20:42, last modified: 02-24-2012 at 01:12_

**Comment by LordBlacksun** [comment]
low priority
