### ISSUE TITLE
Multiple Missile Launch Points

### ISSUE THREAD

**Issue by kgersen** [kgersen/Allegiance#137]
On ship models, there's an indicator for where missiles are launched from (CVH_Missemt, I think. Or MDL_Missemt. At least that's what's used for Milkshape).

Adding multiples should have the ship alternate between firing missiles from those points - IE, the first missile fired would be from missemt1, the second would be from missemt2, and so forth until there were no more.

 _Imported from trac ticket #140,  created by Andon on 07-13-2010 at 20:45, last modified: 02-24-2012 at 07:26_

**Comment by kgersen** [comment]
if we change the names used in mdl we should allow for firing sequences as you hinted.

not only allow firing in sequence, but also allow ships to fire from one or more at the same time in sequence, so, '''missile emitter sub-groups'''.

convention:

Missemt_<groupno>_<seqno>

both group and sequence would increment in the model, however seq. # would not be constrained to uniqueness but group # would be.  

example:

Scout (one missile launcher visible/intended in model):
1) missemt (for backwards compat.) OR Missemt_1_1

Hvy Scout Dual (two missile launchers visible/intended in model):
Two missiles launched would appear to fire simultaneously:
1) missemt_1_1
2) missemt_1_1

Nice Fighter (two missile launchers visible/intended in model):
Firing twice, each missile would emit from alternating launchers:
1) missemt_1_1
2) missemt_1_2

Uber Fighter (four missile launchers visible/intended in model):
Firing twice, each missile would emit from alternating launchers:
1) missemt_1_1
2) missemt_1_2
3) missemt_1_3
4) missemt_1_2

Missile Frig (four missile total launchers, two on left, two on right visible/intended in mode):
Firing twice, two missiles would emit from alternating launchers:
1) missemt_1_1
2) missemt_1_1
3) missemt_2_1
4) missemt_2_1

....

and so on.

this would allow for some pretty cool expansion flexibility.

_Trac comment by Imago on 07-31-2010 at 07:15_

**Comment by LordBlacksun** [comment]
low priority imho
