### ISSUE TITLE
Proximity missiles

### ISSUE THREAD

**Issue by kgersen** [kgersen/Allegiance#159]
AoE missiles currently only create their blast just before they terminate. Missiles only terminate on contact or when they reach their maximum range. 

In addition to the current behavior, missiles with a non-zero Blast Power should terminate IF their target is within their Blast Radius AND the distance to their target is increasing. This will not affect Aleph Res because although Aleph Res has a Blast Radius, like all missiles in existing cores it has a Blast Power of 0.

 _Imported from trac ticket [#159](https://trac.alleg.net//ticket/159),  created by Compellor on 07-21-2010 at 06:30, last modified: 02-24-2012 at 07:33_

**Comment by LordBlacksun** [comment]
low prority
