### ISSUE TITLE
Inputmap on cloud

### ISSUE THREAD

**Issue by kgersen** [kgersen/Allegiance#175]
relates to #147:

<+Imago> what do u think of the idea 
<+Imago> of automatically saving/loading your inputmap
<+Imago> regardless waht artwork or install or where you are
<+Imago> it will pull your inputmap based off your callsign from the server
<+Imago> for the pilot it would'nt be any work at all
<+Imago> and it would save the pain of reconfiguring your controls
<+Imago> i'm strongly considering implementing the get/post for the inputmap ;p
<+Imago> if it didnt pull it in by the time you join a game (not a trianing missino) then it just uses what you got saved last or the default
<+Imago> and once u connect to he lobby is when it trys to posts ur last saved
<+Imago> how does that sound?
<C101_> it sounds like what you are suggesting is a "steam cloud"
<+Imago> see thats why we all need our own kepmaps saved to the cloud1

 _Imported from trac ticket [#176](https://trac.alleg.net//ticket/176),  created by Imago on 07-25-2010 at 13:08, last modified: 02-25-2012 at 16:21_

**Comment by kgersen** [comment]
it's up to you now.

_Trac comment by Imago on 07-28-2010 at 23:24_

**Comment by kgersen** [comment]
i don't know how it could get any better than this, besides paying for more than one storage (inbound) node

_Trac comment by Imago on 07-30-2010 at 09:32_

**Comment by kgersen** [comment]
xynth found a bug.  yay - it's probably with the scramble/unscramble.

_Trac comment by Imago on 08-01-2010 at 19:18_

**Comment by kgersen** [comment]
scramble/unscramble seemed fine - added debugging for Xynth so he can better confirm if there really is an issue.  Please reopen this ticket if so.

_Trac comment by Imago on 08-04-2010 at 01:47_

**Comment by kgersen** [comment]
I will need to see the code behind this.

_Trac comment by Bard on 08-06-2010 at 00:32_

**Comment by kgersen** [comment]
you have access to everything

_Trac comment by anonymous on 08-06-2010 at 00:33_

**Comment by kgersen** [comment]
Replying to [anonymous](comment:8):

> you have access to everything

Where is this particular code? I don't see it and there's nothing here telling me what files to look for.

_Trac comment by Bard on 08-07-2010 at 23:18_

**Comment by kgersen** [comment]
I didn't know I needed to hold your hand or else be accused of being a thief.  I see now that if I do not hold your hand with things you do not want to put forth effort into understanding, you will slander me.  Please don't do that again.  For now, I will take the time to answer your particularly stupid question.

The code is at "Repository Changesets":
r842 r847 r848 r860 r879

The handler is on CDN at C:\Inetpub\wwwroot\build\nph-InputMap.cgi as the code I outlined in the repository suggests.

_Trac comment by anonymous on 08-09-2010 at 19:13_

**Comment by kgersen** [comment]
Code was removed from R6, we need to find a different solution for storing input map.

_Trac comment by pkk on 02-25-2012 at 16:21_

**Comment by LordBlacksun** [comment]
Can't we create a batch script that backups the user's inputmap1.mdl in "my documents/allegbackup" when run?

**Comment by LordBlacksun** [comment]
@echo off
xcopy /W “C:\Program Files(x86)\Microsoft Games\Allegiance 1.2\Production\Artwork/inputmap1.mdl" C:/Users/My Documents

**Comment by kgersen** [comment]
imho, this is very low priority and depends on a much needed major reorganization of artwork files and game files in general.

Meanwhile ACSS could handle this. it's easier to do from it. so better open that issue on ACSS issue list.
