### ISSUE TITLE
"AllegSkill" autobalance improvement

### ISSUE THREAD

**Issue by kgersen** [kgersen/Allegiance#191]
Thread:
http://www.freeallegiance.org/forums/index.php?showtopic=58232

the.ynik concocted a new autobalance algorithm that considers player count, team rank, average player rank, and some flexibility when allowing a player to join a team.

This is an alternative to and/or starting block for AllegSkill-based autobalance which may or may not ever happen.

My rendition of his algorithm is attached; I haven't tested it much because I can't seem to get ranks to work on my LAN.

 _Imported from trac ticket [#192](https://trac.alleg.net//ticket/192),  created by TurkeyXIII on 07-29-2010 at 08:44, last modified: 09-01-2012 at 21:32_

**Comment by kgersen** [comment]
The weighting factors and other constants in the equation can be modified by creating a file called balance.txt in the server's artwork. This file should also contain a rank threshold as per [[https://github.com/kgersen/AllegianceTest/issues/168\]]

_Trac comment by TurkeyXIII on 07-29-2010 at 09:55_

**Comment by kgersen** [comment]
Sgt_Baker approves appending additional rank data in the callsign (for http service fail over and interim testing).

ex.

Imago(0)(43.23)(12.31)
RANK MU SIGMA

<Sgt_Baker> Add it yourself and attribute it to Sgt_Baker

Using a proxy lastMu and lastSigma with TrueSkill is better than what we have now and will put into place the code needed when the actual Mu and Sigma are obtained from the live data source.

_Trac comment by Imago on 07-31-2010 at 19:56_

**Comment by kgersen** [comment]
format now planned is:

+123456789012@ABCD(30)1234 5678
<token><name><rank><mu> <sigma>

_Trac comment by Imago on 08-01-2010 at 17:25_

**Comment by kgersen** [comment]
The replacement GetPlayerRank service is active on both CDN and Beta servers for testing.  CDN is producing debug info for later review to ensure everything is A1, which seems so.

The next steps are to implement pre-launch and post-launch autobalance functions that use the ppso.mu & sigma.  Also we cant forget to set these autobalance functions to be the default setting for new games.

_Trac comment by Imago on 08-04-2010 at 01:50_

**Comment by kgersen** [comment]
I renamed the ticket as it's indeed turning into the long awaited AllegSkill AB impl. which uses mu and sigma.

_Trac comment by Imago on 08-04-2010 at 01:58_

**Comment by kgersen** [comment]
rankscale .6 should be coded as max(RankID) / TRUE_SKILL_MAX (50)

_Trac comment by Imago on 08-04-2010 at 05:12_

**Comment by kgersen** [comment]
once we can remove the fail-over (backwards compat.) /w ASGS we can reduce per player over the wire size to 20B (remove rank)

_Trac comment by Imago on 08-04-2010 at 05:25_

**Comment by kgersen** [comment]
RankISScaled should be an On/Off setting in balance so the same code works either way.

_Trac comment by Imago on 08-04-2010 at 05:32_

**Comment by kgersen** [comment]
unscaled team conservative rank = sumMu - kfactor \* sqrt(sumSigmaSquared)

_Trac comment by Imago on 08-04-2010 at 05:39_

**Comment by kgersen** [comment]
sumSquaredSigma += Math.Pow(player.sigma, 2.0)

_Trac comment by Imago on 08-04-2010 at 05:43_

**Comment by kgersen** [comment]
post-launch AllegSkill Position Request logic will be available after full testing is complete

_Trac comment by Imago on 08-09-2010 at 00:22_

**Comment by kgersen** [comment]
Code was removed, code will be reused with ACSS.

_Trac comment by pkk on 02-25-2012 at 15:36_

**Comment by kgersen** [comment]
Also see #326 - poll players before the autobalance process to see if they'd like to participate.

_Trac comment by Spunky on 09-01-2012 at 21:32_

**Comment by LordBlacksun** [comment]
low priority
