### ISSUE TITLE
BackPort Allegiance

### ISSUE THREAD

**Issue by BigBetaTester** [kgersen/Allegiance#222]
Objective:  revert to build that contains the Dx7 (R4) version and then port forward (cherry pick?), bypassing the Dx9 merge and future enhancements specific to Dx9... thus; bringing the Dx7 version up to date where the Dx7 build then can coexist with the online servers and ACSS.

Should be an option during launch...ie "Dx7.exe or Dx9.exe" as ACSS has now from drop down menu.

This would provide a working exe for those who suffer from the adverse affects that Dx9 builds introduced.  It would return precision to game controllers and smoothness in game play & eliminate stuttering.

**Comment by LordBlacksun** [comment]
I agree.  we should also eliminate the performance issues we encountered  in the current DX7 implementation.

**Comment by kgersen** [comment]
This is not an 'issue' per se. It's a possible solution to another issue ( #223 ) that is not yet fully understood.
